### List all messages
GET http://localhost:3000/messages

### List all messages
POST http://localhost:3000/messages
Content-Type: application/json

{
    "content": "hi there"
}

### List all messages
GET http://localhost:3000/messages/123